#!/usr/bin/env bash
#
# The first and only parameter of this script must be the file with
# the list of englishWords to translate


rm russianFrecVoc.csv

# To clean up the input file , no undesired space, the last s/$// deletes the carriage return generated on windows systems
sed -E '/^$/d;s/ +, +/g,/;s/^ +//;s/ +$//;s/$//;y/ЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ/йцукенгшщзхъфывапролджэячсмитьбю/' $1 > in.csv
i=1
while IFS= read -r line
do
    echo Iteracion: ${i}
    ((i=i+1))
    # ./scripts/webScrapper $(echo $line | awk -F, '{print $1}' - )
    # ipa=$(python3 scripts/IPAScrapper.py)
    # a=$(python3 scripts/AudioScrapper.py)
    # audio=$(echo "<audio controls><source src=\"\"https:${a}\"\" type=\"\"audio/ogg\"\"></audio>")
    englishWord=$(csvawk '{print $2}' <<< "$line")
    russianWord=$(csvawk '{print $1}' <<< "$line" | sed 's/^"//;s/"$//')
    firstRusWord=$(awk -F'[/, ]' '{print $1}' <<< "$russianWord")
    echo ${firstRusWord}
    ./scripts/webScrapper $(echo ${firstRusWord})
    ipa=$(python3 scripts/IPAScrapper.py)
    a=$(python3 scripts/AudioScrapper.py)
    audio=$(echo "<audio controls><source src=\"\"https:${a}\"\" type=\"\"audio/ogg\"\"></audio>")
    ans="<a href=\"\"https://en.wiktionary.org/wiki/${firstRusWord}#Russian\"\">${russianWord}</a>"
    openRussian=$(echo "<a href=\"\"https://en.openrussian.org/ru/${firstRusWord}\"\"><sup><small>[openrussian]</small></sup></a> ")
    tab=$(cat new.html)
    tags=$(echo $line | awk -F, '{print $3}' - )
    example=$(csvawk '{print $4}' <<< "$line" | sed 's/^"//;s/"$//')
    exampleTrad=$(csvawk '{print $5}' <<< "$line" | sed 's/^"//;s/"$//')
    if [[ -n "$example" ]]; then
        yandexLink="<a href=\"\"https://translate.yandex.com/?lang=ru-en&text=${example}\"\">[yandx]</a>"
    else
        yandexLink="<a href=\"\"https://translate.yandex.com/?lang=ru-en&text=${firstRusWord}\"\">[yandx]</a>"
    fi
    phraseRus=$(echo ${example} | sed -E 's/([[:alpha:]]*-?[[:alpha:]]*)/<a href=\"\"https:\/\/en.wiktionary.org\/wiki\/\1#Russian\"\">\1<\/a>/g')
    # echo $example $exampleTrad
    echo "${englishWord},\"<p>${ans}${openRussian} IPA:${ipa} ${audio}</p><p>${phraseRus}</p><p>${yandexLink}</p><p>${exampleTrad}</p> ${tab}\",${tags}" >> russianFrecVoc.csv
done <<< $(cat in.csv)
rm test.html test1.html new.html in.csv
