#!/usr/bin/env bash
#
# The first and only parameter of this script must be the file with
# the list of words to translate


rm out.csv

# To clean up the input file , no undesired space, the last s/$// deletes the carriage return generated on windows systems
sed -E '/^$/d;s/ +, +/g,/;s/^ +//;s/ +$//;s/$//' $1 > in.csv

while IFS= read -r line
do
    ./scripts/webScrapper $(echo $line | awk -F, '{print $1}' - )
    ipa=$(python3 scripts/IPAScrapper.py)
    a=$(python3 scripts/AudioScrapper.py)
    audio=$(echo "<audio controls><source src=\"\"https:${a}\"\" type=\"\"audio/ogg\"\"></audio>")
    word=$(echo $line | awk -F, '{print $2}' -)
    trad=$(echo $line | awk -F, '{print $1}' -)
    ans="<a href=\"\"https://en.wiktionary.org/wiki/${trad}#Russian\"\">${trad}</a>"
    openRussian=$(echo "<a href=\"\"https://en.openrussian.org/ru/${trad}\"\"><sup><small>[openrussian]</small></sup></a> ")
    tab=$(cat new.html)
    tags=$(echo $line | awk -F, '{print $3}' - )
    echo "${word},\"${ans}${openRussian} IPA:${ipa} ${audio} ${tab}\",${tags}" >> out.csv
done <<< $(cat in.csv)
rm test.html test1.html new.html in.csv
